
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock
 

development:
  <<: *default
  database: furima-40103_development

test:
  <<: *default
  database: furima-40103_test

production:
  <<: *default
  database: furima_40103_support_production
  username: furima_40103_support
  password: <%= ENV["FURIMA_40103_SUPPORT_DATABASE_PASSWORD"] %>
